<Project>
    <Import Project="Directory.Build.props.user" Condition="Exists('Directory.Build.props.user')" />

    <!-- MSBuild doesn't pass properties defined in .csproj to project references, so we have to define it here -->
    <PropertyGroup Condition="'$(UnityAssembliesDir)' == '' and '$(BeatSaberDir)' != ''">
        <UnityAssembliesDir>$(BeatSaberDir)/Beat Saber_Data/Managed</UnityAssembliesDir>
    </PropertyGroup>
    <PropertyGroup Condition="'$(BeatSaberDir)' != '' and !$(Configuration.Contains('Editor'))">
        <EnableFrameworkPathOverride>true</EnableFrameworkPathOverride>
        <FrameworkPathOverride>$(BeatSaberDir)/Beat Saber_Data/Managed</FrameworkPathOverride>
    </PropertyGroup>
    <ItemGroup Condition="'$(BeatSaberDir)' != '' and !$(Configuration.Contains('Editor'))">
        <Reference Include="netstandard" HintPath="$(BeatSaberDir)/Beat Saber_Data/Managed/netstandard.dll" Private="false" />
    </ItemGroup>
</Project>
