<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GameDirectory>D:\BSManager\BSInstances\1.45.1</GameDirectory>
        <ImportBSMTTargets>false</ImportBSMTTargets>
        <DisableCopyToGame Condition="!$(Configuration.Contains('Editor'))">false</DisableCopyToGame>
        <DisableCopyToGame Condition="$(Configuration.Contains('Editor'))">true</DisableCopyToGame>
        <TargetFramework>net48</TargetFramework>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <AssemblyName>Reactive</AssemblyName>
        <RootNamespace>Reactive</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BeatSaberModdingTools.Tasks" Version="2.0.0-beta7" PrivateAssets="all" IncludeAssets="build;contentfiles;analyzers;buildtransitive" />
        <Reference Include="UnityEngine">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.UIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.UIElementsModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.InputModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(UnityAssembliesDir)/UnityEngine.ImageConversionModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
